apiVersion: v1
kind: Pod
metadata:
  labels:
    run: secretpod2
  name: secretpod2
spec:
  containers:
  - image: nginx
    name: secretpod2
    env:
     - name: DB_USER
       valueFrom: 
         secretKeyRef:
           name: secret2
           key: user2
     - name: DB_PASSWORD
       valueFrom:
         secretKeyRef: 
           name: secret2
           key: password2